<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-16T22:04:55 EDT" name="RegressionTest" finished-at="2024-04-16T22:05:08 EDT" duration-ms="12807">
    <groups>
      <group name="regression">
        <method signature="LoginTest.invalidPasswordLogin()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" name="invalidPasswordLogin" class="com.neotech.testcases.LoginTest"/>
        <method signature="LoginTest.validLogin()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" name="validLogin" class="com.neotech.testcases.LoginTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="LoginTest.validLogin()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" name="validLogin" class="com.neotech.testcases.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-04-16T22:04:55 EDT" name="Regression" finished-at="2024-04-16T22:05:08 EDT" duration-ms="12807">
      <class name="com.neotech.testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:04:55 EDT" name="setUp" finished-at="2024-04-16T22:04:59 EDT" duration-ms="3358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="invalidPasswordLogin()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:04:59 EDT" name="invalidPasswordLogin" finished-at="2024-04-16T22:05:02 EDT" duration-ms="2812" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error messages do NOT match!!! expected [Invalid Credentials - ] but found [Invalid Credentials]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error messages do NOT match!!! expected [Invalid Credentials - ] but found [Invalid Credentials]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.neotech.testcases.LoginTest.invalidPasswordLogin(LoginTest.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPasswordLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:05:02 EDT" name="tearDown" finished-at="2024-04-16T22:05:02 EDT" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:05:02 EDT" name="setUp" finished-at="2024-04-16T22:05:04 EDT" duration-ms="2643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLogin()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:05:04 EDT" name="validLogin" finished-at="2024-04-16T22:05:08 EDT" duration-ms="3602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.neotech.testcases.LoginTest@350aac89]" started-at="2024-04-16T22:05:08 EDT" name="tearDown" finished-at="2024-04-16T22:05:08 EDT" duration-ms="143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.neotech.testcases.LoginTest -->
    </test> <!-- Regression -->
  </suite> <!-- RegressionTest -->
</testng-results>
